services:
  - type: web
    name: aleron-mp3-downloader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    buildpacks:
      - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
      - type: python